---
- name: Add nodejs apt key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
- name: Add nodejs
  apt_repository:
    repo: "deb https://deb.nodesource.com/{{ VERSION }} {{ DISTRO }} main"
    update_cache: yes
- name: Install nodejs
  apt:
    update_cache: yes
    name: nodejs
    state: present
- name: Install NPM-distributed command-line tools
  npm:
    global: yes
    name: "{{ item }}"
  with_items: " {{ npm_global_modules }}"
- name: Increase de amount of max_user_watches to avoid ENOSPC limit error
  shell: |
    echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
    sudo sysctl -p
